name: ëŒ€í•œë¯¼êµ­ í–‰ì •ë™ ë°ì´í„° ìˆ˜ì§‘
on: [push]
  # schedule:
  #   - crone: '0 0 * * *' # ë§¤ì¼ 0ì‹œ 0ë¶„ì— ì‹¤í–‰
jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Run Cralwer
      run: go run ./cmd/main.go
      
    - name: result data copy to submodule
      run: cp administrationCode.tsv ./administrationCode/
      
    - name: Deploy ğŸš€
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        branch: main
        folder: administrationCode
        ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
