name: 대한민국 행정동 데이터 수집
on: [push]
  # schedule:
  #   - crone: '0 0 * * *' # 매일 0시 0분에 실행
jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Run Cralwer
      run: go run ./cmd/main.go

    - name: clone submodule
      uses: actions/checkout@v2
      with:
        repository: kr-juso/administrationCode
        path: path
        ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        persist-credentials: true

    - name: checkout submodule
      run: |
        git submodule init
        git submodule update
      
    - name: result data copy to submodule
      run: cp administrationCode.tsv ./administrationCode/
      
    - name: push submodule
      run: |
        cd administrationCode
        git commit -m "update data"
        git push
