name: 대한민국 행정동 데이터 수집
on: [push]
  # schedule:
  #   - crone: '0 0 * * *' # 매일 0시 0분에 실행
jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Run Cralwer
      run: go run ./cmd/main.go
      
    - name: result data copy to submodule
      run: cp administrationCode.tsv ./administrationCode/
      
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
         key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
         name: id_rsa # optional
         known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.KNOWN_HOSTS }} >> ~/.ssh/known_hosts
      
    - name: push submodule
      env:
        SSH_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      run: |
        cd administrationCode
        git config --global user.email "kyc1682@gmail.com"
        git config --global user.name "YeongCheon Kim"
        git add administrationCode.tsv
        git commit -m "update data"
        git push origin HEAD:main
